language: node_js
script : 
  - npm test
  - node_modules/.bin/jshint src
  - node_modules/.bin/jsdoc src
node_js:
  - 8
deploy:
  provider: pages,
  skip-cleanup: true,
  github-token: $GITHUB_TOKEN,
  keep-history: true,
  local-dir: out,
  on :
branch: master

